import React, { useEffect } from "react";
import Navbar from "../../components/navbar";
import ScreenSlider from "../../components/screenslider";
// import Gellary from "../components/gellary";
// import SearchBar from "../components/searchBar";
import TopBuilders from "../../components/topBuilders";
// import FAQs from "../components/FAQs";
import BuildingOptions from "../../components/options/buildingOptions";
import { allServices } from "../../Data/DataList";

function Services() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const Services = [
    "HOUSE BUILDING",
    "HOUSE RENOVATION",
    "HOUSE REPAIR",
    "ADVISE FROM EXPERT",
    "ARCHITECT",
    "PACKAGE AND MOVER",
    "GENERAL CONTRACTOR",
    "INTERIOR DESIGNER",
    "CARPENTER",
    "PAINTER",
    "CONSTRUCTION WORKER",
    "BUILDING INSPECTOR",
    "ELECTRICIAN",
    "Basement Renovation",
    "Bathroom Renovation",
    "Decks",
    "Demolition",
    "Elevators, Lifts & Ramps Installation & Service",
    "Historical Restoration",
    "Home Additions",
    "Home Office Renovation",
    "Kitchen Planning & Renovation",
    "Renovation Cleaning",
    "Architects",
    "Builders",
    "Concrete Contractors",
    "Design/Build",
    "Design/Project Management",
    "Drafting Service",
    "General Contractors",
    "Renovation Advisors",
    "Structural Engineering",
    "Bathroom & Kitchen - Fixtures & Accessories",
    "Cabinetry",
    "Carpenters",
    "Closet & Storage Solutions",
    "Elevators, Lifts & Ramps Installation & Service",
    "Framing",
    "Kitchen & Bathroom - Cabinets & Design",
    "Railings",
    "Stair Builders",
    "Woodworking",
    "Carpet & Rug Cleaning & Repairing",
    "Fire & Water Damage Restoration",
    "House & Apartment Cleaning",
    "House Cleaning Exteriors",
    "Junk Removal",
    "Renovation Cleaning",
    "Septic Tank Cleaning, Repair & Installation",
    "Tile and Grout Cleaning",
    "Window Cleaning",
    "Chimney Build & Repair",
    "Chimney Build & Repair",
    "Chimney Sweeps",
    "Bathroom & Kitchen - Fixtures & Accessories",
    "Game Rooms, Entertainment",
    "Garage Design & Organization",
    "Home Staging",
    "Interior Decorators",
    "Interior Design",
    "Kitchen & Bathroom - Cabinets & Design",
    "Alarm Systems",
    "Appliance Repair",
    "Computer Repairs and Support",
    "Electricians",
    "Electronic Repairs",
    "Home Automation",
    "Home Theater",
    "Vacuum Sales & Service",
    "Flooring",
    "Carpet Installers",
    "Concrete Contractors",
    "Decorative Concrete",
    "Floor Laying & Refinishing",
    "Waterproofing",
    "Furniture Designers & Custom Builders",
    "Furniture Refinish & Repair",
    "Furniture Rental",
    "Home Staging",
    "Garage",
    "Closet & Storage Solutions",
    "Garage Design & Organization",
    "Garage Doors & Hardware",
    "Junk Removal",
    "Moving & Storage",
    "Green Products & Services",
    "Solar Panels",
    "Solar Water Heating",
    "Appliance Repair",
    "Building Supplies and Hardware",
    "Electricians",
    "Lighting",
    "Paint & Wallpaper Contractors",
    "Plumbing",
    "Duct Cleaning",
    "Gas Line Installation",
    "Heating & Air Conditioning",
    "Concrete Contractors",
    "Decorative Concrete",
    "Excavation",
    "Fences & Gates",
    "Garden Maintenance",
    "Landscape Architects",
    "Landscape Contractors & Designers",
    "Landscape Lighting",
    "Lawn Maintenance",
    "Swimming Pools, Spas & Hot Tubs",
    "Tree Service",
    "Closet & Storage Solutions",
    "Junk Removal",
    "Moving & Storage",
    "Plumbing",
    "Drain Services",
    "Drainage Contractors",
    "Excavation",
    "Tank Cleaning, Repair",
    "Sprinkler Systems",
    "Water Filtration & Purification",
  ];
  const heading = "Our All Services";
  return (
    <>
      <ScreenSlider />
      <BuildingOptions options={allServices} heading={heading} />
    </>
  );
}

export default Services;
